stages:
  - coding_convention

.coding_convention:
  stage: coding_convention
  image: ruby:2.6.5
  before_script:
    - gem install bundler --no-document
    - bundle install
  script:
    - bundle exec rubocop .