image: 2.6.5

stages:
  - coding_convention
  - automation_deploy
  - manual_deploy

before_script:
  - gem install bundler --no-document
  - bundle install

coding_convention:
  stage: coding_convention
  image: ruby:2.6.5
  script:
    - bundle exec rubocop .
  when: always
  except:
    - staging

.setup_deployment:
  script:
    - apt-get update && apt-get -y install openssh-client
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)

automation_deploy:
  stage: automation_deploy
  before_script:
    - echo "Auto deploying api for staging environment"
    - !reference [.setup_deployment, script]
  script:
    - sed -i 's/auction-staging/${AUCTION_STAGING_IP}/g' config/deploy/staging.rb
    - bundle exec cap staging deploy
  when: on_success
  only:
    - staging

manual_deploy:
  stage: manual_deploy
  before_script:
    - echo "Manual deploy api for production environment"
    - !reference [.setup_deployment, script]
  script:
    - sed -i 's/auction-production/${AUCTION_PRODUCTION_IP}/g' config/deploy/production.rb
    - bundle exec cap production deploy
  when: manual
  only:
    - master