image: ruby:2.6.5

stages:
  - coding_convention
  - automation_deploy
  - manual_deploy

.ruby_setup:
  script:
    - gem install bundler --no-document
    - bundle install

.setup_deployment:
  script:
    - apt-get update && apt-get -y install openssh-client
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)

coding_convention:
  stage: coding_convention
  before_script:
    - echo "Check coding convention using rubocop"
    - !reference [.ruby_setup, script]
  script:
    - bundle exec rubocop .
  when: always

automation_deploy:
  stage: automation_deploy
  before_script:
    - echo "Auto deploying api for staging environment"
    - !reference [.ruby_setup, script]
    - !reference [.setup_deployment, script]
  script:
    - bundle exec cap staging deploy
  when: on_success
  only:
    - staging

manual_deploy:
  stage: manual_deploy
  before_script:
    - echo "Manual deploy api for production environment"
    - !reference [.ruby_setup, script]
    - !reference [.setup_deployment, script]
  script:
    - bundle exec cap production deploy
  when: manual
  only:
    - master