token_time:
  normal: 1 # week
  reset_password: 15 # minutes
  verify_otp: 5 # minutes

validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    password_regex: !ruby/regexp '/^(?=.*[A-Z])(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\W]).{8,}$/'
